name: Builds CLI and SDK binaries.

on:
  workflow_call:
    inputs: {}
    secrets: {}
  push:
    tags:
      - explicit_build_yml*

env:
  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

jobs:
  # TODO flag for goreleaser params
  # TODO re-enable darwin in Goreleaser config, test out on darwin worker
  build_pulumi_go_binaries:
    name: Builds Pulumi Go binaries
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repo
        uses: actions/checkout@v2
        with:
          ref: ${{ env.PR_COMMIT_SHA }}
      - name: Fetch Tags
        run: |
          git fetch --quiet --prune --unshallow --tags
      - name: Install pulumictl
        uses: jaxxstorm/action-install-gh-release@v1.2.0
        with:
          repo: pulumi/pulumictl
      - name: Set up Go 1.17.x
        uses: actions/setup-go@v1
        with:
          go-version: 1.17.x
      - name: Compute current version to inform GoReleaser
        run: |
          echo "GORELEASER_CURRENT_TAG=v$(pulumictl get version --language generic -o)" >> $GITHUB_ENV
      - name: Run GoReleaser to build Go Pulumi binaries
        uses: goreleaser/goreleaser-action@v2
        with:
          version: latest
          args: -p 3 -f .goreleaser.build.yml --skip-validate
      - name: Upload Go Pulumi binaries to share with other jobs
        uses: actions/upload-artifact@v2
        with:
            name: pulumi-go-binaries
            path: goreleaser/
