name: Builds CLI and SDK binaries.

on:
  workflow_call:
    inputs:
      go-version:
        description: 'Version of the Go toolchain for the build'
        default: '1.17.x'
        required: false
        type: string
      goreleaser-flags:
        description: 'Command-line flags to pass to goreleaser'
        default: '-p 3 -f .goreleaser.build.yml --skip-validate'
        required: false
        type: string
      go-binaries-artifact-name:
        description: 'Name for the artifact containing Go binaries'
        default: 'pulumi-go-binaries'
        required: false
        type: string
    secrets: {}

env:
  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

jobs:
  build_pulumi_go_binaries:
    name: Build Pulumi Go binaries

    # Due to the use of CGO in `pulumi` this cross-compilation step
    # cannot proceed on `ubuntu-latest`, which would have been
    # preferable.
    runs-on: macos-latest
    steps:
      - name: Checkout Repo
        uses: actions/checkout@v2
        with:
          ref: ${{ env.PR_COMMIT_SHA }}
      - name: Fetch Tags
        run: |
          git fetch --quiet --prune --unshallow --tags
      - name: Install pulumictl
        uses: jaxxstorm/action-install-gh-release@v1.2.0
        with:
          repo: pulumi/pulumictl
      - name: Set up Go ${{ inputs.go-version }}
        uses: actions/setup-go@v1
        with:
          go-version: ${{ inputs.go-version }}
      - name: Compute current version to inform GoReleaser
        run: |
          echo "GORELEASER_CURRENT_TAG=v$(pulumictl get version --language generic -o)" >> $GITHUB_ENV
      - name: Run GoReleaser to build Go Pulumi binaries
        uses: goreleaser/goreleaser-action@v2
        with:
          version: latest
          args: ${{ inputs.goreleaser-flags }}
      - name: Upload Go Pulumi binaries to share with other jobs
        uses: actions/upload-artifact@v2
        with:
            name: ${{ inputs.go-binaries-artifact-name }}
            path: goreleaser/
